version: '3'
services:
  composer:
    image: herloct/composer:1.3.2-php5.6
    volumes:
      - .:/project

  codecept:
    image: php:5.6.30
    working_dir: /project
    entrypoint:
      - php
      - vendor/bin/codecept
    volumes:
      - .:/project

  phpcbf:
    image: herloct/phpcbf:2.8.1
    volumes:
      - .:/project
